import { Category, MessData } from "@/types";

export const MESS_INFO: MessData = {
  name: "ছাত্রাবাস স্মাট মেস",
  type: "BOYS_MESS",
  owner: {
    name: "Abir Hasan",
    phone: "+8801712345678",
  },
  address: {
    street: "House 12, Road 7",
    area: "Uttara Sector 10",
    city: "Dhaka",
    postalCode: 1230,
  },
  phone: "+880961234567",
};

export const FOOD_CATEGORIES: Category[] = [
  {
    id: 1,
    title: "তেল/মশলা",
    items: [
      {
        id: 1,
        name: "সয়াবিন তেল",
        price: 100,
        unite: "লিটার",
        bld: { breakfast: true, lunch: false, dinner: true, editable: false },
        pp: 10,
      },
      {
        id: 2,
        name: "সরিষার তেল",
        price: 80,
        unite: "লিটার",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 3,
        name: "পাম তেল",
        price: 90,
        unite: "লিটার",
        bld: { breakfast: true, lunch: true, dinner: false, editable: false },
      },
      {
        id: 4,
        name: "কোকোনাট তেল",
        price: 120,
        unite: "লিটার",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 5,
        name: "ঘি",
        price: 200,
        unite: "লিটার",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 6,
        name: "বাটার",
        price: 150,
        unite: "লিটার",
        bld: { breakfast: false, lunch: true, dinner: true, editable: false },
      },
      {
        id: 7,
        name: "চিনি",
        price: 50,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 8,
        name: "লবণ",
        price: 20,
        unite: "কেজি",
        bld: {
          breakfast: false,
          lunch: false,
          dinner: false,
          editable: false,
        },
      },
    ],
  },
  {
    id: 2,
    title: "শাক",
    items: [
      {
        id: 9,
        name: "পালং শাক",
        price: 20,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 10,
        name: "লাল শাক",
        price: 25,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 11,
        name: "কলমি শাক",
        price: 18,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 12,
        name: "পুঁই শাক",
        price: 22,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: true, editable: true },
      },
      {
        id: 13,
        name: "ঝিঙ্গে শাক",
        price: 28,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: false, editable: true },
      },
      {
        id: 14,
        name: "নটে শাক",
        price: 19,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 15,
        name: "শ্যাম শাক",
        price: 30,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 16,
        name: "সরিষা শাক",
        price: 26,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
    ],
  },
  {
    id: 3,
    title: "সবজি",
    items: [
      {
        id: 17,
        name: "আলু",
        price: 30,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 18,
        name: "বেগুন",
        price: 35,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 19,
        name: "টমেটো",
        price: 40,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 20,
        name: "শসা",
        price: 25,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 21,
        name: "করলা",
        price: 32,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 22,
        name: "মিষ্টি কুমড়া",
        price: 27,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 23,
        name: "পটল",
        price: 34,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 24,
        name: "কাঁচা মরিচ",
        price: 80,
        unite: "কেজি",
        bld: {
          breakfast: false,
          lunch: false,
          dinner: false,
          editable: false,
        },
      },
    ],
  },
  {
    id: 4,
    title: "মাছ",
    items: [
      {
        id: 25,
        name: "রুই মাছ",
        price: 250,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 26,
        name: "ইলিশ মাছ",
        price: 800,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: false },
      },
      {
        id: 27,
        name: "কাতলা",
        price: 300,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: false, editable: true },
      },
      {
        id: 28,
        name: "পাবদা",
        price: 350,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 29,
        name: "টেংরা",
        price: 400,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 30,
        name: "চিংড়ি",
        price: 600,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 31,
        name: "মাগুর মাছ",
        price: 450,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: false, editable: true },
      },
      {
        id: 32,
        name: "সিলভার কার্প",
        price: 220,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
    ],
  },
  {
    id: 5,
    title: "মাংস",
    items: [
      {
        id: 33,
        name: "গরুর মাংস",
        price: 700,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 34,
        name: "মুরগি",
        price: 180,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 35,
        name: "খাসির মাংস",
        price: 850,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 36,
        name: "হাঁস",
        price: 400,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: true, editable: true },
      },
      {
        id: 37,
        name: "মুরগি লেগ পিস",
        price: 200,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 38,
        name: "চিকেন উইংস",
        price: 210,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 39,
        name: "মুরগি বুকের মাংস",
        price: 220,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: true },
      },
      {
        id: 40,
        name: "হাড় ছাড়া মাংস",
        price: 260,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
    ],
  },
  {
    id: 6,
    title: "নিত্যপ্রয়োজনীয় খাদ্যপণ্য",
    items: [
      {
        id: 41,
        name: "চাল",
        price: 60,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: true, editable: false },
      },
      {
        id: 42,
        name: "ডাল",
        price: 90,
        unite: "কেজি",
        bld: { breakfast: false, lunch: false, dinner: true, editable: true },
      },
      {
        id: 43,
        name: "চিনি",
        price: 55,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: true, editable: false },
      },
      {
        id: 44,
        name: "আটা",
        price: 45,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: true, editable: true },
      },
      {
        id: 45,
        name: "ময়দা",
        price: 50,
        unite: "কেজি",
        bld: { breakfast: true, lunch: true, dinner: false, editable: true },
      },
      {
        id: 46,
        name: "চিড়া",
        price: 35,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
      {
        id: 47,
        name: "সুজি",
        price: 40,
        unite: "কেজি",
        bld: { breakfast: false, lunch: true, dinner: false, editable: true },
      },
      {
        id: 48,
        name: "মুড়ি",
        price: 30,
        unite: "কেজি",
        bld: { breakfast: true, lunch: false, dinner: false, editable: true },
      },
    ],
  },
];

/**
 * Budget status thresholds
 */
export const BUDGET_THRESHOLDS = {
  LOW_REMAINING: 0.2, // 20% remaining budget threshold
  HIGH_UTILIZATION: 0.8, // 80% budget utilization threshold
} as const;
